//! Integration tests for `vento-file-parser`.
//!
//! Exercises the `FileParser` end-to-end against a representative sample from
//! each container family: PDF, DOCX, XLSX, PPTX, ODT, RTF, CSV, EPUB, and
//! plain text. The non-PDF fixtures are generated by
//! `tests/fixtures-gen/generate.py`; PDF fixtures are checked in under
//! `tests/fixtures/`. The tests assert that:
//!
//! 1. conversion succeeds and produces non-empty markdown;
//! 2. the `decisions` list contains the expected action for the format
//!    (extract for text-bearing containers);
//! 3. the result metadata round-trips: filename, size, mime, duration.
//!
//! The HTTP OCR provider is not exercised here — it would require a live
//! PaddleOCR endpoint or a stub HTTP server. The embedded-image OCR pass is
//! covered with an in-process stub provider, and the `OcrRequired` error by a
//! small unit test inside the crate.

use std::path::PathBuf;

use vento_file_parser::{ConvertOptions, DocumentInput, FileParser, RuntimeError};

fn fixtures_root() -> PathBuf {
    // tests/ lives at the workspace root, parallel to crates/.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .join("tests/fixtures-gen/samples")
}

fn pdf_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .join("crates/pdf-engine/tests/fixtures")
}

async fn convert_path(path: PathBuf) -> vento_file_parser::ConvertResult {
    let parser = FileParser::new();
    parser
        .convert(DocumentInput::Path { path }, ConvertOptions::default())
        .await
        .unwrap_or_else(|err| panic!("conversion failed: {err}"))
}

fn assert_extract_decision(result: &vento_file_parser::ConvertResult, target: &str) {
    let decision = result
        .decisions
        .iter()
        .find(|d| d.target == target)
        .unwrap_or_else(|| {
            panic!(
                "missing decision for target {target}: {:?}",
                result.decisions
            )
        });
    assert_eq!(
        decision.action, "extract",
        "expected extract, got {:?}",
        decision
    );
}

#[tokio::test]
async fn converts_plain_csv() {
    let path = fixtures_root().join("employee-directory.csv");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "csv markdown is empty");
    assert!(
        result.markdown.contains("Ada Lovelace"),
        "csv markdown missing name"
    );
    assert_extract_decision(&result, "employee-directory.csv");
    assert!(result.source.size > 0);
}

#[tokio::test]
async fn converts_rtf() {
    let path = fixtures_root().join("memo.rtf");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "rtf markdown is empty");
    assert!(
        result.markdown.contains("Engineering Memo"),
        "rtf missing title"
    );
    assert_extract_decision(&result, "memo.rtf");
}

#[tokio::test]
async fn converts_docx_with_table() {
    let path = fixtures_root().join("company-handbook.docx");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "docx markdown is empty");
    assert!(
        result.markdown.contains("Ventorium Employee Handbook"),
        "docx missing title"
    );
    assert!(
        result.markdown.contains("Onboarding Checklist"),
        "docx missing H2"
    );
    assert!(
        result.markdown.contains("Day 1") || result.markdown.contains("Week 1"),
        "docx missing table cell"
    );
    assert_extract_decision(&result, "company-handbook.docx");
    assert_eq!(
        result.source.mime_type,
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    );
}

#[tokio::test]
async fn converts_xlsx_to_markdown_table() {
    let path = fixtures_root().join("quarterly-revenue.xlsx");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "xlsx markdown is empty");
    assert!(result.markdown.contains("Quarter"), "xlsx missing header");
    assert!(
        result.markdown.contains("1200000") || result.markdown.contains("1,200,000"),
        "xlsx missing value"
    );
    assert_extract_decision(&result, "quarterly-revenue.xlsx");
}

#[tokio::test]
async fn converts_pptx_slides() {
    let path = fixtures_root().join("quarterly-review.pptx");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "pptx markdown is empty");
    assert!(
        result.markdown.contains("Quarterly Review"),
        "pptx missing slide 1 title"
    );
    assert!(
        result.markdown.contains("Roadmap"),
        "pptx missing slide 2 title"
    );
    assert_extract_decision(&result, "quarterly-review.pptx");
}

#[tokio::test]
async fn converts_odt() {
    let path = fixtures_root().join("release-notes.odt");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "odt markdown is empty");
    assert!(
        result.markdown.contains("Release Notes"),
        "odt missing title"
    );
    assert_extract_decision(&result, "release-notes.odt");
}

#[tokio::test]
async fn converts_epub_chapter() {
    let path = fixtures_root().join("field-guide.epub");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "epub markdown is empty");
    assert!(
        result.markdown.contains("Onboarding"),
        "epub missing chapter text"
    );
    assert_extract_decision(&result, "field-guide.epub");
}

#[tokio::test]
async fn converts_text_pdf() {
    // firecrawl_docs_tagged.pdf is a small tagged text PDF that pdf-inspector
    // extracts cleanly without OCR.
    let path = pdf_root().join("firecrawl_docs_tagged.pdf");
    let result = convert_path(path).await;
    assert!(!result.markdown.is_empty(), "pdf markdown is empty");
    assert!(
        result.markdown.len() > 100,
        "pdf markdown suspiciously short"
    );
    assert!(
        result.decisions.iter().any(|d| d.action == "extract"),
        "pdf should produce an extract decision"
    );
}

#[tokio::test]
async fn pdf_metadata_includes_page_count() {
    let path = pdf_root().join("nexo-price-en.pdf");
    let result = convert_path(path).await;
    // The wrapper records the page count only on the OCR-required path; the
    // happy path is allowed to omit it. Just confirm the convert succeeded
    // and produced markdown of meaningful size.
    assert!(!result.markdown.is_empty());
    assert!(result.source.size > 0);
}

#[tokio::test]
async fn converts_plain_text_passthrough() {
    let parser = FileParser::new();
    let result = parser
        .convert(
            DocumentInput::Bytes {
                data: b"Plain notes.\nLine two.".to_vec(),
                file_name: "notes.txt".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .unwrap();
    assert_eq!(result.markdown, "Plain notes.\nLine two.");
    assert_extract_decision(&result, "notes.txt");
    assert_eq!(result.source.mime_type, "text/plain");
}

#[tokio::test]
async fn converts_markdown_verbatim() {
    let parser = FileParser::new();
    let source = "# Title\n\nBody with `code`.\n";
    let result = parser
        .convert(
            DocumentInput::Bytes {
                data: source.as_bytes().to_vec(),
                file_name: "README.md".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .unwrap();
    assert_eq!(result.markdown, source);
}

#[tokio::test]
async fn converts_json_to_fenced_block() {
    let parser = FileParser::new();
    let result = parser
        .convert(
            DocumentInput::Bytes {
                data: b"{\"key\": \"value\"}".to_vec(),
                file_name: "config.json".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .unwrap();
    assert_eq!(result.markdown, "```json\n{\"key\": \"value\"}\n```\n");
}

#[tokio::test]
async fn non_utf8_text_errors_cleanly() {
    let parser = FileParser::new();
    let err = parser
        .convert(
            DocumentInput::Bytes {
                data: vec![0xFF, 0xFE, 0x00, 0x01],
                file_name: "blob.txt".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .expect_err("expected unsupported for non-UTF-8 text");
    assert!(matches!(err, RuntimeError::Unsupported(_)), "got {err:?}");
}

#[tokio::test]
async fn unsupported_format_errors_cleanly() {
    let parser = FileParser::new();
    // Random bytes that match no known container signature, with an
    // extension that names no supported format.
    let bytes = b"this is not a document of any known format".to_vec();
    let err = parser
        .convert(
            DocumentInput::Bytes {
                data: bytes,
                file_name: "noise.bin".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .expect_err("expected unsupported error");
    assert!(matches!(err, RuntimeError::Unsupported(_)), "got {err:?}");
    assert_eq!(err.code(), "UNSUPPORTED");
}

#[tokio::test]
async fn image_without_ocr_provider_reports_ocr_required() {
    let parser = FileParser::new();
    // 1x1 PNG signature + IHDR chunk; valid header bytes but not a real image
    // would still trip detection through Format::from_extension. Build a real
    // 1x1 PNG with python-style minimal bytes.
    let bytes: Vec<u8> = vec![
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG signature
        0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, // IHDR length + name
        0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, // 1x1
        0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4, 0x89, 0x00, 0x00, 0x00, 0x0A, 0x49, 0x44,
        0x41, 0x54, 0x78, 0x9C, 0x63, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01, 0x0D, 0x0A, 0x2D,
        0xB4, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
    ];
    let err = parser
        .convert(
            DocumentInput::Bytes {
                data: bytes,
                file_name: "pixel.png".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .expect_err("expected OcrRequired for image input");
    assert!(
        matches!(err, RuntimeError::OcrRequired { .. }),
        "got {err:?}"
    );
    assert_eq!(err.code(), "OCR_REQUIRED");
}

/// An embedded image's recognized text is emitted as an annotation block
/// after its marker — never inside the alt text, where brackets, pipes and
/// newlines in the OCR output would break the surrounding Markdown.
#[tokio::test]
async fn embedded_image_ocr_becomes_an_annotation_block() {
    struct StubProvider;

    #[async_trait::async_trait]
    impl vento_file_parser::OcrProvider for StubProvider {
        fn name(&self) -> &'static str {
            "stub"
        }

        async fn recognize(
            &self,
            _request: vento_file_parser::OcrRequest,
            _options: vento_file_parser::OcrOptions,
        ) -> Result<vento_file_parser::OcrOutput, vento_file_parser::OcrError> {
            Ok(vento_file_parser::OcrOutput {
                markdown: "# 标题\n\n| a | b |".into(),
                confidence: None,
                provider: "stub".into(),
            })
        }
    }

    // The parser fixtures live next to this crate, not in the generated set.
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/docx/handmade-rich.docx");
    let bytes = std::fs::read(path).unwrap();
    let parser = FileParser::new().with_ocr(std::sync::Arc::new(StubProvider));
    let result = parser
        .convert(
            DocumentInput::Bytes {
                data: bytes,
                file_name: "handmade-rich.docx".into(),
            },
            ConvertOptions::default(),
        )
        .await
        .expect("conversion succeeds");

    assert!(
        result.markdown.contains("![图片1：tiny dot image]()"),
        "alt keeps the number and drops the OCR text:\n{}",
        result.markdown
    );
    assert!(
        result
            .markdown
            .contains("> 图片1的OCR解析结果如下：\n>\n> # 标题\n>\n> | a | b |"),
        "recognized text follows the image as a quoted block:\n{}",
        result.markdown
    );
}
