/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function convertBytes(data: Buffer, fileName: string, optionsJson?: string | undefined | null): Promise<string>

export declare function supportedFormats(): string
