[package]
name = "vento-agentd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
serde_json.workspace = true
nix.workspace = true
tokio.workspace = true
vsock.workspace = true
vento-agent-protocol.workspace = true
vento-runtime-types.workspace = true
