/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function requestRuntime(baseUrl: string, token: string, method: string, path: string, bodyJson?: string | undefined | null): Promise<string>

export declare function requestRuntimeBinary(baseUrl: string, token: string, method: string, path: string, body?: Buffer | undefined | null): Promise<Buffer>

export declare function startLocalRuntime(binaryPath: string, listen: string, token: string, configPath?: string | undefined | null): number
