name: linux-kvm

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  integration:
    runs-on: [self-hosted, linux, kvm]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.1
      - run: cargo test --workspace --release -- --ignored

